---
type: journal
date: 2004-09-01
title: "Creating data services in new democracies. Experiences from a case study and related neighbours"
author:
  - name: Adrian Dușa
    url: https://adriandusa.eu
    orcid: 0000-0002-3525-9253
    attributes:
      corresponding: true
    affiliation: Department of Sociology, University of Bucharest
    affiliation-url: https://sas.unibuc.ro/en
categories:
  - RODA
pub-info:
  links:
    - name: Journal
      url: https://onlinelibrary.wiley.com/doi/abs/10.1111/j.1468-2451.2003.05503005.x
      icon: fa-solid fa-scroll
    - name: PDF
      url: 2004-ISSJ.pdf
      icon: fa-solid fa-file-pdf
citation:
  type: article-journal
  url: https://onlinelibrary.wiley.com/doi/abs/10.1111/j.1468-2451.2003.05503005.x
  publisher: "ISSJ"
  container-title: "International Social Science Journal"
  volume: 55
  issue: 177
  page: 401-405
  doi: 10.1111/j.1468-2451.2003.05503005.x
---

## Abstract

In Romania, as in other former communist countries, there has long been a deficit of information about social research and its data. In light of the growing need for high-quality data, which are a pre-condition for effective social policies, solutions to address the deficit are currently being sought both nationally and internationally. The article summarises the recent establishment of the Romanian Social Data Archive, which is supported by the Institute for Quality of Life Research (an institute of the Romanian Academy of Sciences) and by the Faculty of Sociology and Social Work of the University of Bucharest and points to the main technical and legal challenges that it faces. Indications about collaborative activities are also provided, pointing to the common problems raised by social science data in Eastern Europe and the considerable scope for cooperation in addressing them.
