project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  google-analytics: "G-5B3S7E955Z"
  favicon: "images/favicon.png"
  twitter-card: true
  title: "Adrian Dușa"
  navbar:
    pinned: true
    search: true
    collapse: true
    left:
      - href: index.qmd
        text: About
      - href: blog/index.qmd
        text: Blog
      - href: research/index.qmd
        text: Research
      - href: "cv/index.qmd"
        text: CV

  page-footer:
    left: |
      <span class="faux-block">{{< fa brands creative-commons >}} {{< var years >}} Adrian Dușa</span>
      <span class="faux-block">All content licensed under<br>[{{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}} Creative Commons CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)</span>
    center: |
      <span class="faux-block">{{< fa brands orcid >}} <strong>ORCID</strong> [{{< var orcid >}}](https://orcid.org/{{< var orcid >}})</span>
      <span class="faux-block">{{< fa key >}} [PGP public key]({{< var pgp.key >}}) &emsp; {{< fa fingerprint >}} Fingerprint:</strong><br><span class="fingerprint">{{< var pgp.fingerprint >}}</span></span>
    right: |
      <span class="faux-block">Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)</span>
      <span class="faux-block">[View the source at {{< fa brands github >}} GitHub]({{< var github-url >}})</span>

format:
  html:
    theme: html/custom.scss
    css: html/styles.css
    toc: true


editor: visual
